# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('base_quantity', models.IntegerField(default=1)),
                ('quantity_unit', models.CharField(default='', max_length=20)),
                ('rate', models.CharField(default='', max_length=20)),
                ('photo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
