# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
