# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
